export const GET_PRODUCTS_BEGIN = 'GET_PRODUCTS_BEGIN';
export const LOAD_PRODUCTS = 'LOAD_PRODUCTS'
export const SET_GRIDVIEW = 'SET_GRIDVIEW'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'

